export const GET_POKEMON_DETAILS = 'GET_POKEMON_DETAILS'
export const FEED_DETAILS = 'FEED_DETAILS'
export const GET_DETAILS_FAIL = 'GET_DETAILS_FAIL'
export const DETAILS_SUCCESS="DETAILS_SUCCESS"
export const BACK_TO_PREV="BACK_TO_PREV"